version: '3.7'
services:
  openldap:
    image: osixia/openldap:latest
    container_name: openldap
    hostname: openldap
    volumes:
      - ./data/certificates:/container/service/slapd/assets/certs
      - ./data/slapd/database:/var/lib/ldap
      - ./data/slapd/config:/etc/ldap/slapd.d
    environment:
      - LDAP_ORGANISATION=yourOrganisation
      - LDAP_DOMAIN=yourOrganisation.loc
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=admin
      - LDAP_CONFIG_PASSWORD=config_pass
      - "LDAP_BASE_DN=dc=yourOrganisation,dc=loc"
      - LDAP_TLS_CRT_FILENAME=server.crt
      - LDAP_TLS_KEY_FILENAME=server.key
      - LDAP_TLS_CA_CRT_FILENAME=yourOrganisation.com.ca.crt
      - LDAP_READONLY_USER=true
      - LDAP_READONLY_USER_USERNAME=user-read-only
      - LDAP_READONLY_USER_PASSWORD=user-read-only
    networks:
      - ldapnet

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    hostname: phpldapadmin
    ports:
      - "8081:80"
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
      - PHPLDAPADMIN_HTTPS=false
    depends_on:
      - openldap
    networks:
      - ldapnet
    
  backend:
    container_name: backend
    hostname: backend
    depends_on:
      - openldap

    environment:
      - "Encryption:Key=DigitalerSchülerausweis"
      - "Encryption:IV=1234567891011112"
      - "Ldap:Credentials:Domain=dc=yourOrganisation,dc=loc"
      - "Ldap:Credentials:User=cn=user-read-only"
      - "Ldap:Credentials:Password=user-read-only"
      - "Ldap:Server:Hostname=openldap"
      - "Ldap:Server:Port=389"
      - "TokenLifeSpan:Days=0"
      - "TokenLifeSpan:Hours=0"
      - "TokenLifeSpan:Minutes=3"
      - "TokenLifeSpan:Seconds"
    build:
      context: ./Schuelerausweis
      dockerfile: ./Schuelerausweis/Dockerfile
    networks:
      - ldapnet
      
  frontend:
    container_name: frontend
    build: ./SchuelerausweisWeb
    ports:
      - 9000:80
    environment:
      - "ENCRYPTION_ALGO=aes-128-cbc"
      - "ENCRYPTION_KEY=DigitalerSchülerausweis"
      - "ENCRYPTION_IV=1234567891011112"
      - "LDAP_SERVER_HOSTNAME=openldap"
      - "LDAP_SERVER_PORT=389"
      - "LDAP_BASE_DN=dc=yourOrganisation,dc=loc"
      - "WEB_API_PATH=http://backend/api/User"
    depends_on:
      - backend
    networks:
      - ldapnet

networks:
  ldapnet:
    driver: bridge
